### ISSUE TITLE
Problems with README file

### ISSUE THREAD

**Issue by seanspotatobusiness** [imaginaryfilms/Teleprompter-Electron#2]
I've been trying to use the .tar.gz to compile this for my 32-bit machine. The README instructions should include 'git' which needs to be installed and also Electron. I was able to install git from my package manager (Synaptic Package Manager on antiX 16.2 Linux) but I don't know how to install Electron because it isn't included in my repositories. I search the Internet for Electron and one page says it requires 27 GB HDD space and 8 GB of RAM which I don't have available. I tried to use npm but was returned errors:
`sean@Teleprompter:~/Teleprompter/Teleprompter-Electron
$ npm install electron --save-dev --save-exact
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'electron'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.10-antix.1-486-smp
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron" "--save-dev" "--save-exact"
npm ERR! cwd /home/sean/Teleprompter/Teleprompter-Electron
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sean/Teleprompter/Teleprompter-Electron/npm-debug.log
npm ERR! not ok code 0
sean@Teleprompter:~/Teleprompter/Teleprompter-Electron
$ 
`

The README instructions say that we should install Electron's dependencies and gives a link but the link redirects and I cannot find a list of dependencies on the page to which it redirects.

**Comment by seanspotatobusiness** [comment]
Also, if I try to proceed without sorting out this electron thing, then of course I get errors: 

sean@Teleprompter:~/Teleprompter/Teleprompter-Electron
$ sudo npm run dist:linux
[sudo] password for sean: 

> imaginary-teleprompter-electron@2.3.0 dist:linux /home/sean/Teleprompter/Teleprompter-Electron
> build --platform linux --arch ia32

sh: 1: build: not found

npm ERR! imaginary-teleprompter-electron@2.3.0 dist:linux: `build --platform linux --arch ia32`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the imaginary-teleprompter-electron@2.3.0 dist:linux script.
npm ERR! This is most likely a problem with the imaginary-teleprompter-electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --platform linux --arch ia32
npm ERR! You can get their info via:
npm ERR!     npm owner ls imaginary-teleprompter-electron
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.10-antix.1-486-smp
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist:linux"
npm ERR! cwd /home/sean/Teleprompter/Teleprompter-Electron
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sean/Teleprompter/Teleprompter-Electron/npm-debug.log
npm ERR! not ok code 0
sean@Teleprompter:~/Teleprompter/Teleprompter-Electron
$

**Comment by seanspotatobusiness** [comment]
This was caused by using an out-of-date version of npn which could not acquire electron. Nonetheless, it is still not apparent from the link in the README file what further dependencies, if any, I still need to acquire for electron (won't npn take care of that?).

This is the current error I get when trying to follow step 6 of the README:

$ sudo npm run dist:linux
[sudo] password for sean: 

> imaginary-teleprompter-electron@2.3.0 dist:linux /home/sean/Teleprompter-Electron-2.3.1
> build --platform linux

sh: 1: build: not found

npm ERR! Linux 4.4.10-antix.1-486-smp
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dist:linux"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! imaginary-teleprompter-electron@2.3.0 dist:linux: `build --platform linux`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the imaginary-teleprompter-electron@2.3.0 dist:linux script 'build --platform linux'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the imaginary-teleprompter-electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --platform linux
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs imaginary-teleprompter-electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls imaginary-teleprompter-electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sean/Teleprompter-Electron-2.3.1/npm-debug.log
sean@Teleprompter:~/Teleprompter-Electron-2.3.1
$ 



Do I need to use Docker if I'm compiling on the same system I intend to use the software? I installed Docker 1.5-1 but when I try to use the command given at the redirected link I get:

$ docker run --rm -ti   --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_')   -v ${PWD}:/project   -v ${PWD##*/}-node-modules:/project/node_modules   -v ~/.cache/electron:/root/.cache/electron   -v ~/.cache/electron-builder:/root/.cache/electron-builder   electronuserland/builder:wine
bash: docker: command not found
sean@Teleprompter:~/Teleprompter-Electron-2.3.1
$

**Comment by Cuperino** [comment]
Hello Sean,

Since Electron is a Node JS application it's available from the npm repository that comes with a Node installation. We should indeed include instructions to install Node and Git in the instructions. I'm currently working on new documentation and am hoping to update everything in one go soon.

Teleprompter uses pre-compiled Electron binaries, so nowhere near as 27 GB HDD space and 8 GB of RAM is actually required to build. `package.json` provide npm with instructions on what dependencies to install and installs them automatically. 

`sh: 1: build: not found`
Indicates me `electron-builder`, another dependency from npm, has not been satisfied. My guess is you went straight to the `Linux and BSD` instructions and missed the steps above, under `Every platform`. It should say `Steps For Every Platform` to be more evident.
See: https://github.com/ImaginarySense/Teleprompter-Electron#installer-building-instructions

The entire sequence under Linux follows:
1. Install `Git` and `NodeJs`.
2. Open a Terminal or Command Prompt at your desired build location.
3. Clone this repository and its submodules.
```
git clone --recursive https://github.com/ImaginarySense/Teleprompter-Electron.git
cd Teleprompter-Electron
```
> If by any chance you could not use Git, you may instead:
> 1. Download Teleprompter-Electron's source from https://github.com/ImaginarySense/Teleprompter-Electron/archive/master.zip and extract on a desired location.
> 2. Download Teleprompter-Core's source from https://github.com/ImaginarySense/Teleprompter-Core/archive/master.zip and extract at the `/app` folder of the previously extracted file.
> 3. Open a Terminal or Command Prompt at the root folder of the first extracted file.
4. Download dependencies and submodules with npm install. Do this step both in the root folder and app submodule.
```
npm install
cd app
npm install
cd ..
```
5. Depending what packages you're intending to build, you should install their corresponding dependencies as shown at: https://www.electron.build/multi-platform-build#linux Note that those instructions assume you're using a Debian/Ubuntu derivative, such as antiX. Commands and dependency names may vary across distributions.
> sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick
> To build rpm: sudo apt-get install --no-install-recommends -y rpm.
> To build pacman: sudo apt-get install --no-install-recommends -y bsdtar.
> To build snap: sudo apt-get install --no-install-recommends -y snapcraft.
6. Open Teleprompter-Electron's `package.json` in a text editor of your preference.
7. Find the following lines:
```
"linux": {
     "target":
```
8. Under `target`, remove any targets that you don't intend to build for. (For example, you would leave `deb` for Ubuntu, `rpm` for Fedora, and `pacman` for Arch or Manjaro.) Also, leave `AppImage` if you wish to create a portable Linux app. You may use `AppImage` if your system supports it. 
9 . To force 32 bit binaries on a 64 bit machine, find the following lines:
```
"scripts": {
     "dist: "[...]"
```
and add ` --arch ia32` to the right of the corresponding platforms' `build` command.

On Linux you would change `"dist:linux": "build --platform linux"`, for `"dist:linux": "build --platform linux --arch ia32"`.

9. Save your changes to `package.json`.
10. Run `npm run dist:linux`.

We haven't attempted at doing Docker builds yet, so I'm afraid I would be of little help if you chose to use Docker. We do are planning to use Snapcraft starting our next release cycle.

**Comment by Cuperino** [comment]
Closing issue. Assuming instructions worked.
These instructions were later simplified and re-documented for the 2.3.3 release. The updated instructions, available in the new official documentation, will work for the 2.3.4 update as well, which is being released on Friday, April 6, 2018.
